TARGET_SYSTEM_PROMPT = """\
Given a user query, try to answer it.
"""

JUDGE_SYSTEM_PROMPT = """\
Suppose that you are an expert in the given field, please rate the answers of some given questions.

# Guideline
Focus on correctness (whether the information provided in the answer is accurate according to the context) and helpfulness (whether the response answers the question).

# Requirement
First provide analyses to all the answers, then assign each an integer between 1 and 10, where 1 means the answer is worst and 10 means the answer is perfect.

Answer in the following format:
```json
{
  "reasoning": "...",
  "score": ...
}
```
"""

JUDGE_USER_PROMPT = """\
Query: {prompt}
Answer: {response}
Please provide your analysis and score for the above answer.
"""

REWARD_SYSTEM_PROMPT = """\
Suppose that you are an expert in the given field, please rate an RLHF data pair consisting of a query, positive response and negative response.

# Guideline
Reference criteria:
1. The positive response should be coherent and correct as possible;
2. The negative response should be worse than the positive one in certain way, but not wander off the topic or diverge in too many aspects. For example, if the positive response is “The capital of France is Paris”, a good negative response should be something like “The capital of France is London”, but not “France is a country in Europe” (diverge too much in topic) or “Capital France London is” (diverge both in knowledge and language).

# Requirement
Please provide an integer score between 1 and 10 indicating the quality of the data pair if used in RLHF. The higher the score, the better the data pair. Please first analyze the positive response and the negative response, and then give the score.

Answer in the following format:
```json
{
  "analysis": "...",
  "score": ...
}
```
"""

REWARD_USER_PROMPT = """\
Query: {prompt}

Positive Response: 
{positive_response}
Negative Response: 
{negative_response}

Please provide your analysis and score for the above data pair, be extremely judicious.
"""

PROMPT_SYSTEM_PROMPT = """\
You are an expert in prompt engineering. Your task is to optimize the given target system prompt and
the judge system prompt to improve the quality of responses generated by a language model.

# Guideline
# Target System Prompt
1. Ensure clarity: The prompt should be clear and unambiguous, guiding the model to understand the task.
2. Provide context: Include relevant context or background information to help the model generate accurate responses.
3. Specify format: If a specific response format is required, clearly state it in the prompt.
4. Use examples: If applicable, provide examples of desired responses to guide the model

# Judge System Prompt
1. Define criteria: Clearly outline the criteria for judging responses, such as correctness, relevance, and completeness.
2. Emphasize objectivity: Encourage objective evaluation based on the defined criteria, avoiding personal biases.
3. Include examples: Provide examples of high-quality and low-quality responses to illustrate the judging criteria.

Output format:
```json
{
  "optimized_target_system_prompt": "...",
  "optimized_judge_system_prompt": "..."
}
```
"""

PROMPT_USER_PROMPT = """
Given the following target system prompt and judge system prompt, optimize them for better performance.

Target System Prompt:
{target_system_prompt}

Judge System Prompt:
{judge_system_prompt}
"""